GET http://localhost:3001/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjg1LCJ1c2VybmFtZSI6ImFkbWluaXN0cmF0b3IiLCJpYXQiOjE2NDQ4ODk5MTUsImV4cCI6MTY0NDg4OTkzMH0.PM5ojROTrKHkxaV2pCKJIEP4Q6boAJ1yBiiTd0VhcPY
###

POST http://localhost:3001/login
Content-Type: application/json

{
"USER_PASS": "Asd!59789",
"USER_NAME": "administrator"
}
###
GET http://localhost:3001/token
###
DELETE  http://localhost:3001/logout
###
GET http://localhost:3001/user/1
###

###
GET http://localhost:3001/dept/1

###
GET http://localhost:3001/menu
###



POST http://localhost:3001/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjc3LCJ1c2VybmFtZSI6ImxvZG9uZyIsImlhdCI6MTY0NDgyMzYzMiwiZXhwIjoxNjQ0ODIzNjUyfQ.GSpyuhNDQBC1UXGAvLSmgQQBNDOj96LAOTYkfBIYRA0

{
"USER_INISIAL": "administrator",
"USER_PASS": "Asd!59789",
"USER_NAME": "administrator",
"USER_EMAIL": "admin@cpm.com",
"USER_DEP": 0,
"USER_JAB": 0,
"USER_LEVEL": "LEVEL",
"USER_FLAG": "D",
"USER_AKTIF_STATUS": 1,
"USER_DELETE_STATUS": 0,
"USER_ADD_ID": "1" 
}




###
PATCH  http://localhost:3001/user/87
Content-Type: application/json

{
"USER_INISIAL": "egifilth",
"USER_INISIAL": "egi",
"USER_PASS": "3331",
"USER_NAME": "FERRY",
"USER_EMAIL": "egi@gmail.com",
"USER_DEP": 0,
"USER_JAB": 0,
"USER_LEVEL": "LEVEL",
"USER_FLAG": "D",
"USER_AKTIF_STATUS": 0,
"USER_DELETE_STATUS": 0,
"USER_ADD_ID": "1" 
}

###
PATCH  http://localhost:3001/user/delete/36
Content-Type: application/json

{
"USER_DELETE_STATUS": 1
}

###

GET http://localhost:3001/useraccess/37
###

GET http://localhost:3001/useraccess/menuview/85

###
POST  http://localhost:3001/useraccess/2/5
Content-Type: application/json

{
    "USER_ID": 2,
    "MENU_ID": 5,
    "USER_ACESS_VIEW": null,
    "USER_ACESS_ADD": null,
    "USER_ACESS_MOD": null,
    "USER_ACESS_DELETE": null,
    "USER_ACESS_PRINT": null
}

# {
# "USER_ID" : 2,
# "MENU_ID" : 3,
# "USER_ACESS_VIEW" : 1,
# "USER_ACESS_ADD" : 0
# }

# {
# "MENU_ID" : 3,
# "USER_ACESS_ADD" : 1,
# "USER_ACESS_DELETE" : 1,
# "USER_ACESS_MOD" : null,
# "USER_ACESS_PRINT" : null,
# "USER_ACESS_VIEW" : 1,
# "USER_ID": 2
# }


###
GET http://localhost:3001/header/30/

###
POST  http://localhost:3001/header
Content-Type: application/json

{
    "header_add_id": 90,
"header_dept_id": 1,
"header_id": 55,
"header_leader": "maman",
"header_operator": "jajang,maman",
"header_prod_date": "2022-03-21",
"header_shift": "2"
}
###
POST   http://localhost:3001/header
Content-Type: application/json

{
   "header_add_id": 90,
"header_dept_id": 1,
"header_leader": "monang",
"header_operator": "maman,jajang",
"header_prod_date": "2022-03-22",
 "header_mod_id": 90,
"header_shift": "1"
}

###
GET http://localhost:3001/header/report/2022-03-25

###
GET http://localhost:3001/mixer/product/2022-03-22
###

GET http://localhost:3001/mixer/batch/2022-03-09
###

GET http://localhost:3001/getform/MIXER_CHECK
###

GET http://localhost:3001/mixer/batch/procheck/39/1
###

GET http://localhost:3001/mixer/batch/2022-03-09
###

GET http://localhost:3001/mixer/batch/MIXER_CHECK/1
###

POST  http://localhost:3001/mixer/batch/procheck
Content-Type: application/json

{
    "header_id" : 39,
    "batch_regis_id" : 4,
    "mixer_proc_chek_date" : "2022-03-13",
    "mixer_proc_chek_shift" : "1",
    "mixer_proc_chek_add_id" : 90
}
###

POST  http://localhost:3001/mixer/batch/checklist
Content-Type: application/json

{
    "mixer_proc_check_id" : 53,
    "standar_form_id" : 2,
    "standar_form_value" : 33
}


###
GET http://localhost:3001/formula/1

###
PATCH  http://localhost:3001/formula/1
Content-Type: application/json

{
    "batch_regis_prod_flag": "Y"
}
###
GET http://localhost:3001/downtime
###

POST http://localhost:3001/downtime
Content-Type: application/json

{
    "downtime_id" : 1,
    "downtime_dept_id": 1,
    "batch_regis_id": 1,
    "downtime_type": "Mesin Hurung",
    "downtime_start": "09:02:00",
    "downtime_add_remark": "Mesin Giling Mati Total dan Listrik tidak terkoneksi",
    "downtime_add_id": 1
}

###

GET http://localhost:3001/mixer/frmla-params/value/54/9
###

POST http://localhost:3001/mixer/frmla-params
Content-Type: application/json

{
    "mixer_frml_id" : null,
	"standar_form_id" : 1,
	"mixer_frml_params" : "CAI BUKUR",
	"product_id" : 1,
	"header_id" : 1,
	"mixer_frml_add_id" : 1,
	"mixer_frml_mod_id" : 1
}

####
GET http://localhost:3001/formula/chart/2022-03-25
####
###Mixer Report Get Product Chart
GET http://localhost:3001/mixer/report/product/2022-03-22/%%/9% 
####
###MIxer report get detail batch
GET http://localhost:3001/mixer/report/2022-03-22/%%/%9%

###
###Mixer Report Get Sequence Data
GET http://localhost:3001/mixer/report/sequence/2022-03-25/%2%/%

####
GET http://localhost:3001/mixer/report/sequence/2022-03-25/%%/%

###
GET http://localhost:3001/mixer/report/time/30/9/10

###
###
GET http://localhost:3001/mixer/report/master/2022-03-22
###
GET http://localhost:3001/forming/product/2022-03-22
